### PR TITLE
ofxTrueTypeFontUC for Android

### PR DESCRIPTION
**Pull request by noyanc**
1. Android os doesn't have a freetype2 implementation. The usage of ofxTrueTypeFontUC in Android projects needs the prebuilt freetype2 libraries to be included to the ofxTrueTypeFontUC implementation. We built these libraries for armeabi, armeabi-v7a and x86 architectures. Thanks to these prebuilts, we are now succesfully using ofxTrueTypeFontUC addon in our Android game.

2. These methods are added to the source file: ofxTrueTypeFontUC.stringWidth(const string &str) and ofxTrueTypeFontUC.stringHeight(const string &str)

### CODE REVIEW

**Comment by hironishihara** [comment]
Thank you for your contribution.

The ofxTruetypefontUC addon is used in combination with openFrameworks, and openFrameworks 0.8.4 for android has included freetype2 implementation.
So, I don't think that this addon should have individually freetype2 implementation.

Regarding stringWidth() and stringHeight(), I’ve not realized that these implementations are missing.
I will marge it.

I’m glad to hear that this addon is used in your android game!

**Comment by hironishihara** [comment]
Thank you for your contribution.

The ofxTrueTypeFontUC addon is used in combination with openFrameworks, and openFrameworks 0.8.4 for android has included freetype2 implementation.
So, I don't think that this addon should have individually freetype2 implementation.

Regarding stringWidth() and stringHeight(), I’ve not realized that these implementations are missing.
I will marge it.

I’m glad to hear that this addon is used in your android game!

**Comment by noyanc** [comment]
Hi, it would be great if you can kindly merge stringWidth() and stringHeight() methods. Regards.

**Comment by hironishihara** [comment]
Hi, your commit was already merged to master 6 months ago.
Thank you again, @noyanc .

**Pull request closed without merging**
